# OPT-125M -> OPT-6.7B
family: opt
weak:
  name: facebook/opt-125m
  short: ${basename:${model.weak.name}}
strong:
  name: facebook/opt-6.7b
  short: ${basename:${model.strong.name}}
lora_target_modules: [q_proj, v_proj]
