enabled: true
project: ms-po
entity: ${oc.env:WANDB_ENTITY,null}
group: ${dataset.name}-${model.weak.short}-to-${model.strong.short}
tags: ["${dataset.name}", "${model.family}", "${method.name}", "${loss.name}"]
